-- MINIMSAAH — seed content (Way A full dump, update-by-email, nothing breaks)
-- Run AFTER supabase/auth-migrate.js (Auth creates new UUIDs, this preserves them).
-- Order: schema.sql -> rls.sql -> storage.sql -> auth-migrate.js -> THIS file.
-- Idempotent: ON CONFLICT DO NOTHING, reruns safe.

INSERT INTO public.articles (id, title, slug, excerpt, body, cover_image, category, tags, author_id, reading_time, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvqw000ce30o8aonkhi2', 'The Hidden Gems of Accra: Grassroots Football academies Reshaping Ghana''s Future', 'the-hidden-gems-of-accra-grassroots-football-academies-reshaping-ghana-s-future', 'Inside the community pitches and makeshift academies where Ghana''s next generation of world-class talent is being forged — no funding, no fame, just raw passion.', 'In the dusty compounds of Jamestown and the narrow streets of Nima, young footballers chase a dream with nothing but a ball and boundless determination.

These grassroots academies operate without the glamour of Europe''s elite youth systems. There are no manicured pitches, no physiotherapists, no video analysis rooms. Yet they produce players who go on to compete at the highest levels.

"We don''t have resources, but we have heart," says Coach Emmanuel Darko, who runs the Osu Youth Development Programme from a converted parking lot. "Every child who walks through our gates gets the same chance — rich or poor, tall or short."

The numbers speak for themselves. Over the past decade, more than 40 Ghanaian players who came through grassroots systems have signed professional contracts abroad. That''s not counting the dozens who''ve become key figures in the Ghana Premier League.

The real challenge, according to scouts who''ve visited these programmes, isn''t finding talent — it''s nurturing it. Without consistent funding, many academies close their doors within two years. Those that survive do so through community donations and the sheer will of their founders.', NULL, 'FEATURE', '{grassroots,academy,ghana,talent}', (SELECT id FROM public.users WHERE email = 'writer@minimsaah.com'), 8, 0, true, 'PUBLISHED', '2026-09-19 12:09:12.625', '2026-09-19 12:09:12.632', '2026-09-19 12:09:12.632') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.articles (id, title, slug, excerpt, body, cover_image, category, tags, author_id, reading_time, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvrc000ge30orpkqoje0', 'Tactical Analysis: Why Ghana''s New 3-5-2 Formation Could Be the Answer', 'tactical-analysis-why-ghana-s-new-3-5-2-formation-could-be-the-answer', 'Coach Otto Addo''s decision to switch to a back three could unlock the potential of Ghana''s wing-backs and finally solve the midfield creativity problem.', 'When Otto Addo unveiled a 3-5-2 formation in the recent friendly against Liberia, few paid much attention. It was, after all, just a test match.

But looking deeper, the tactical shift could be transformative for the Black Stars. The system maximizes the qualities of wing-backs Gideon Mensah and Tariq Lamptey while providing midfield solidity through Thomas Partey''s advanced positioning.

"The beauty of the 3-5-2 is that it creates numerical superiority in midfield while still maintaining width," explains tactical analyst Nii Armah. "With Partey and Kudus operating in the half-spaces, you have two players who can receive between the lines and drive forward."

The formation also addresses Ghana''s persistent vulnerability to counter-attacks. With three centre-backs and two holding midfielders, the defensive structure provides natural cover that the previous 4-2-3-1 lacked.', NULL, 'ANALYSIS', '{analysis,tactics,black-stars,formation}', (SELECT id FROM public.users WHERE email = 'writer@minimsaah.com'), 6, 1, false, 'PUBLISHED', '2026-09-19 12:09:12.647', '2026-09-19 12:09:12.649', '2026-09-19 14:25:39.358') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.articles (id, title, slug, excerpt, body, cover_image, category, tags, author_id, reading_time, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvr9000ee30o83gwzl02', 'Match Report: Hearts of Oak 3-1 Asante Kotoko — A Derby Day Classic', 'match-report-hearts-of-oak-3-1-asante-kotoko-a-derby-day-classic', 'A hat-trick from junior striker Kwesi Afriyie sealed a memorable victory for Hearts of Oak in the biggest fixture of the Ghana Premier League season.', 'Hearts of Oak produced a masterclass performance at the Accra Sports Stadium, defeating rivals Asante Kotoko 3-1 in front of a sellout crowd.

Kwesi Afriyie opened the scoring in the 12th minute with a curling shot from outside the box that left goalkeeper Ibrahim Danlad rooted to the spot. The striker doubled his tally before halftime, latching onto a defence-splitting pass from captain Fatawu Mohammed.

Kotoko pulled one back through Steven Mukwala''s header just after the break, temporarily shifting the momentum. But Afriyie completed his hat-trick in the 71st minute, meeting a corner kick at the near post to send the stadium into delirium.

The victory moves Hearts of Oak to within two points of league leaders Samartex, with a game in hand.', NULL, 'MATCH_REPORT', '{match-report,hearts,kotoko,derby}', (SELECT id FROM public.users WHERE email = 'editor@minimsaah.com'), 5, 1, false, 'PUBLISHED', '2026-09-19 12:09:12.643', '2026-09-19 12:09:12.645', '2026-09-19 17:15:31.453') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.articles (id, title, slug, excerpt, body, cover_image, category, tags, author_id, reading_time, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvrf000ie30o1k93byjv', 'In Conversation with Andre Ayew: Legacy, Leadership, and the Road Ahead', 'in-conversation-with-andre-ayew-legacy-leadership-and-the-road-ahead', 'The Ghana captain opens up about his journey, the weight of the armband, and his plans for the next World Cup cycle.', '"People see the goals and the celebrations," says Andre Ayew, settling into a chair at the Ghana Football Association headquarters in Accra. "They don''t see the 5 AM training sessions when nobody''s watching."

At 35, Ayew remains one of the most influential figures in Ghanaian football. His career has spanned Olympique de Marseille, Swansea City, Al Sadd, and now a return to the Ghana Premier League with Hearts of Oak.

"Coming home was the best decision I''ve made," he says with a smile. "I want to give back what this country gave me."

Ayew''s leadership extends beyond the pitch. Through the Ayew Foundation, he''s funded the construction of three football pitches in Accra and sponsored 50 young players'' education.

"Football opens doors, but education keeps them open," he says. "Every child in my academy goes to school. That''s non-negotiable."', NULL, 'INTERVIEW', '{interview,ayew,leadership,legacy}', (SELECT id FROM public.users WHERE email = 'writer@minimsaah.com'), 10, 1, false, 'PUBLISHED', '2026-09-19 12:09:12.649', '2026-09-19 12:09:12.651', '2026-09-19 14:32:33.346') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.articles (id, title, slug, excerpt, body, cover_image, category, tags, author_id, reading_time, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvri000ke30oovygw01g', 'The Case for Investment: Why African Football''s Economic Moment Is Now', 'the-case-for-investment-why-african-football-s-economic-moment-is-now', 'With broadcasting rights, sponsorships, and transfer fees skyrocketing, African football is at an inflection point. Those who invest now will reap the rewards.', 'The numbers are staggering. The African football market has grown by 240% in the past five years, driven by broadcasting deals, digital platforms, and a new generation of commercially savvy club administrators.

The English Premier League alone pays over £1.2 billion annually for rights across the African continent. Add in La Liga, Serie A, and the Bundesliga, and you''re looking at a broadcasting ecosystem worth more than $2 billion.

But here''s the real story: the talent export market. African players now command transfer fees that would have been unthinkable a decade ago. Victor Osimhen''s €70 million move to Napoli, Nicolas Pépé''s €72 million to Arsenal — these aren''t outliers anymore. They''re the new baseline.

"Every European scout is now looking at Africa," says investment banker and football consultant Kweku Asante. "The question isn''t whether to invest — it''s how quickly you can move."', 'https://dndiajfohpmnmocmmokt.supabase.co/storage/v1/object/public/minimsaah-media/0be6735e-acf2-4513-aacb-71189871230c.jpg', 'OPINION', '{opinion,investment,business,economics}', (SELECT id FROM public.users WHERE email = 'editor@minimsaah.com'), 7, 9, false, 'PUBLISHED', '2026-09-19 12:09:12.652', '2026-09-19 12:09:12.654', '2026-09-22 23:21:49.472') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.documentaries (id, title, slug, description, cover_image, video_url, embed_url, duration, chapters, tags, author_id, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvry000se30ocgh8tltt', 'The Pitch Beyond: Grassroots Football in Rural Ghana', 'the-pitch-beyond-grassroots-football-in-rural-ghana', 'A 45-minute journey into the heartland of Ghanaian football, where village pitches produce national team stars.', NULL, 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 2700, NULL, '{documentary,grassroots,rural}', (SELECT id FROM public.users WHERE email = 'video@minimsaah.com'), 0, true, 'PUBLISHED', '2026-09-19 12:09:12.668', '2026-09-19 12:09:12.67', '2026-09-19 12:09:12.67') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.documentaries (id, title, slug, description, cover_image, video_url, embed_url, duration, chapters, tags, author_id, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvs5000ue30ocz0z8nb8', 'Kotoko vs Hearts: 50 Years of Rivalry', 'kotoko-vs-hearts-50-years-of-rivalry', 'The definitive documentary on West Africa''s greatest football rivalry, featuring rare archive footage and exclusive interviews.', NULL, 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 3600, NULL, '{documentary,rivalry,history}', (SELECT id FROM public.users WHERE email = 'video@minimsaah.com'), 0, false, 'PUBLISHED', '2026-09-19 12:09:12.676', '2026-09-19 12:09:12.678', '2026-09-19 12:09:12.678') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.documentaries (id, title, slug, description, cover_image, video_url, embed_url, duration, chapters, tags, author_id, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvs8000we30ot8mi0w2r', 'Women''s Game: Rising Voices in Ghanaian Football', 'women-s-game-rising-voices-in-ghanaian-football', 'Three women fighting to transform the landscape of women''s football in Ghana through coaching, administration, and grassroots development.', NULL, 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 2400, NULL, '{documentary,womens-football,empowerment}', (SELECT id FROM public.users WHERE email = 'video@minimsaah.com'), 0, false, 'PUBLISHED', '2026-09-19 12:09:12.678', '2026-09-19 12:09:12.68', '2026-09-19 12:09:12.68') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id, title, slug, description, cover_image, date, end_date, location, venue, ticket_url, tags, author_id, status, created_at, updated_at) VALUES ('cmu8cgvsd000ye30o2jnpxvud', 'Accra Sports Journalism Awards 2026', 'accra-sports-journalism-awards-2026', 'The annual celebration of excellence in Ghanaian sports journalism. Categories include Feature Writing, Photography, and Broadcast.', NULL, '2026-09-15 18:00:00', NULL, 'Accra', 'Kempinski Hotel Gold Coast City', NULL, '{awards,journalism,gala}', (SELECT id FROM public.users WHERE email = 'admin@minimsaah.com'), 'PUBLISHED', '2026-09-19 12:09:12.685', '2026-09-19 12:09:12.685') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id, title, slug, description, cover_image, date, end_date, location, venue, ticket_url, tags, author_id, status, created_at, updated_at) VALUES ('cmu8cgvsl0010e30ouorzlq39', 'MINIMSAAH Grassroots Football Summit', 'minimsaah-grassroots-football-summit', 'A two-day conference bringing together coaches, scouts, and football administrators to discuss the future of youth development in West Africa.', NULL, '2026-10-22 09:00:00', '2026-10-23 17:00:00', 'Kumasi', 'Kumasi Cultural Centre', NULL, '{summit,grassroots,development}', (SELECT id FROM public.users WHERE email = 'admin@minimsaah.com'), 'PUBLISHED', '2026-09-19 12:09:12.694', '2026-09-19 12:09:12.694') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id, title, slug, description, cover_image, date, end_date, location, venue, ticket_url, tags, author_id, status, created_at, updated_at) VALUES ('cmu8cgvsp0012e30owbo4zgzv', 'Live: Ghana vs Morocco — World Cup Qualifier Watch Party', 'live-ghana-vs-morocco-world-cup-qualifier-watch-party', 'Join MINIMSAAH for a live screening of the crucial World Cup qualifier at our Accra office. Expert analysis, half-time breakdowns, and post-match reactions.', NULL, '2026-11-10 20:00:00', NULL, 'Accra', 'MINIMSAAH HQ, East Legon', NULL, '{watch-party,live,world-cup}', (SELECT id FROM public.users WHERE email = 'admin@minimsaah.com'), 'PUBLISHED', '2026-09-19 12:09:12.697', '2026-09-19 12:09:12.697') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.media (id, filename, original_name, mime_type, size, url, alt, caption, type, width, height, uploader_id, created_at) VALUES ('cmu8clak9000ae39kl6jpqh2q', 'b40a89a6-ff09-4fbc-bc96-a392a642e771.png', 'test_upload.png', 'image/png', 68, 'https://dndiajfohpmnmocmmokt.supabase.co/storage/v1/object/public/minimsaah-media/b40a89a6-ff09-4fbc-bc96-a392a642e771.png', NULL, NULL, 'IMAGE', NULL, NULL, (SELECT id FROM public.users WHERE email = 'admin@minimsaah.com'), '2026-09-19 12:12:38.457') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.media (id, filename, original_name, mime_type, size, url, alt, caption, type, width, height, uploader_id, created_at) VALUES ('cmudatbvq000re39k8ucmo2uz', '0be6735e-acf2-4513-aacb-71189871230c.jpg', 'hero-bg.jpg', 'image/jpeg', 340039, 'https://dndiajfohpmnmocmmokt.supabase.co/storage/v1/object/public/minimsaah-media/0be6735e-acf2-4513-aacb-71189871230c.jpg', NULL, NULL, 'IMAGE', NULL, NULL, (SELECT id FROM public.users WHERE email = 'writer@minimsaah.com'), '2026-09-22 23:21:45.062') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.tickers (id, text, link, priority, active, created_at, updated_at) VALUES ('cmu8cgvq90005e30o92gb8v3q', 'Ghana Black Stars secure dramatic 2-1 victory over Nigeria in World Cup qualifier', NULL, 10, true, '2026-09-19 12:09:12.609', '2026-09-19 12:09:12.609') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.tickers (id, text, link, priority, active, created_at, updated_at) VALUES ('cmu8cgvqf0006e30o84r0w4eu', 'Breaking: Asante Kotoko announce new head coach ahead of CAF Champions League campaign', NULL, 9, true, '2026-09-19 12:09:12.616', '2026-09-19 12:09:12.616') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.tickers (id, text, link, priority, active, created_at, updated_at) VALUES ('cmu8cgvqh0007e30ohpd0phdm', 'Transfer Alert: Hearts of Oak confirm interest in Brazilian midfielder', NULL, 8, true, '2026-09-19 12:09:12.618', '2026-09-19 12:09:12.618') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.tickers (id, text, link, priority, active, created_at, updated_at) VALUES ('cmu8cgvqj0008e30osr6hfovf', 'Ghana Premier League matchday 15 results and standings update', NULL, 7, true, '2026-09-19 12:09:12.62', '2026-09-19 12:09:12.62') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.tickers (id, text, link, priority, active, created_at, updated_at) VALUES ('cmu8cgvql0009e30op5um7w55', 'Exclusive: Kumasi Sports Academy receives $2M investment from FIFA Forward programme', NULL, 6, true, '2026-09-19 12:09:12.622', '2026-09-19 12:09:12.622') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.tickers (id, text, link, priority, active, created_at, updated_at) VALUES ('cmu8cgvqo000ae30om6r8kjhh', 'Live: WAFA U-17 squad named for COSAFA Youth Championship', NULL, 5, true, '2026-09-19 12:09:12.624', '2026-09-19 12:09:12.624') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, slug, description, video_url, embed_url, thumbnail, duration, category, tags, author_id, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvrl000me30oscg6x0p7', 'Kwesi Afriyie''s Hat-Trick Highlights — Hearts vs Kotoko', 'kwesi-afriyie-s-hat-trick-highlights-hearts-vs-kotoko', 'All three goals from the youngster''s stunning performance in the Accra derby.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://www.youtube.com/embed/dQw4w9WgXcQ', NULL, 312, 'HIGHLIGHT', '{highlights,derby,hat-trick}', (SELECT id FROM public.users WHERE email = 'video@minimsaah.com'), 0, true, 'PUBLISHED', '2026-09-19 12:09:12.655', '2026-09-19 12:09:12.657', '2026-09-19 12:09:12.657') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, slug, description, video_url, embed_url, thumbnail, duration, category, tags, author_id, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvrt000oe30ovk7t3tgr', 'Training Ground: Inside the Black Stars Camp', 'training-ground-inside-the-black-stars-camp', 'Exclusive behind-the-scenes access to the Ghana national team''s preparation for the World Cup qualifier.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://www.youtube.com/embed/dQw4w9WgXcQ', NULL, 486, 'BEHIND_SCENES', '{behind-the-scenes,national-team,training}', (SELECT id FROM public.users WHERE email = 'video@minimsaah.com'), 0, false, 'PUBLISHED', '2026-09-19 12:09:12.663', '2026-09-19 12:09:12.665', '2026-09-19 12:09:12.665') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, slug, description, video_url, embed_url, thumbnail, duration, category, tags, author_id, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cgvrv000qe30osyqcmbon', 'Scouting Report: 15-Year-Old Midfielder Kofi Mensah', 'scouting-report-15-year-old-midfielder-kofi-mensah', 'Our scouts break down the tape on Ghana''s most exciting young prospect.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://www.youtube.com/embed/dQw4w9WgXcQ', NULL, 624, 'INTERVIEW', '{scouting,youth,prospect}', (SELECT id FROM public.users WHERE email = 'video@minimsaah.com'), 0, false, 'PUBLISHED', '2026-09-19 12:09:12.665', '2026-09-19 12:09:12.667', '2026-09-19 12:09:12.667') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, slug, description, video_url, embed_url, thumbnail, duration, category, tags, author_id, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cl4qf0005e39ktez1rsrv', 'Test YouTube - Black Stars Goal', 'test-youtube-black-stars-goal', 'Test youtube embed stays in site', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ?rel=0&modestbranding=1&playsinline=1', 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg', NULL, 'HIGHLIGHT', '{test,youtube}', (SELECT id FROM public.users WHERE email = 'admin@minimsaah.com'), 1, false, 'PUBLISHED', NULL, '2026-09-19 12:12:30.904', '2026-09-19 12:12:42.795') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, slug, description, video_url, embed_url, thumbnail, duration, category, tags, author_id, view_count, featured, status, published_at, created_at, updated_at) VALUES ('cmu8cl5c90007e39k0co6g017', 'Test TikTok - Street Skills', 'test-tiktok-street-skills', 'Test tiktok', 'https://www.tiktok.com/@khaby.lame/video/7190000000000000000', 'https://www.tiktok.com/embed/7190000000000000000', NULL, NULL, 'BEHIND_SCENES', '{}', (SELECT id FROM public.users WHERE email = 'admin@minimsaah.com'), 2, false, 'PUBLISHED', NULL, '2026-09-19 12:12:31.69', '2026-09-28 11:10:20.297') ON CONFLICT (id) DO NOTHING;

-- ─── Users profile merge by email (names only — passwords live in Supabase Auth, never here) ───
UPDATE public.users SET first_name = 'Kwame', last_name = 'Asante' WHERE email = 'admin@minimsaah.com';
UPDATE public.users SET first_name = 'Ama', last_name = 'Mensah' WHERE email = 'editor@minimsaah.com';
UPDATE public.users SET first_name = 'Kofi', last_name = 'Boateng' WHERE email = 'writer@minimsaah.com';
UPDATE public.users SET first_name = 'Yaa', last_name = 'Owusu' WHERE email = 'video@minimsaah.com';
UPDATE public.users SET first_name = 'Nana', last_name = 'Agyeman' WHERE email = 'fan@minimsaah.com';
